In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
dataset = pd.read_csv('FE_DF_Salida.csv')
dataset.head()

,Technical Program Manager,Solution Architect,Business Analyst,Software Engineer,Software Engineering Manager,Data Scientist,Hardware Engineer,Human ResourcesManagement ConsultantMarketingMechanical Engineer,Product Designer,Product Manager,...,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,Race_Two_Or_More,Race_Black,Race_Hispanic
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.metrics import roc_auc_score

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [19]:
X = dataset.drop(['gender'], axis=1)
y = dataset['gender']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=2022)

In [20]:
svm = GridSearchCV(SVC(), {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}, cv=10).fit(X_train, y_train)
randomForest = GridSearchCV(RandomForestClassifier(), {'n_estimators': [20, 50, 100], 
                                                        'max_depth': [10, 100]}).fit(X_train, y_train)

In [ ]:
svmResults = pd.DataFrame(svm.cv_results_)
svmResults.sort_values('rank_test_score', ascending=True)

In [ ]:
randomForest.cv_results_